### ISSUE TITLE
TA-Lib issue

### ISSUE THREAD

**Issue by guiramos** [edyatl/qqe-mod#1]
Hello good sir.

Do you happen to have a more updated version of this script, for python 3.1X? 
Having an incredible hard time to install ta-lib.

**Comment by edyatl** [comment]
Thank you for reaching out and for your interest in the Python porting of the QQE MOD by Mihkel00 TradingView Indicator project.

Regarding your question about TA-Lib installation, I understand that you are having trouble installing TA-Lib, which is required by the Python TA-Lib wrapper used in the project.

To install TA-Lib, you have a couple of options:

1. Build from source: You can build TA-Lib from source by following the instructions on the TA-Lib GitHub repository: https://github.com/mrjbq7/ta-lib
2. Binaries installation: You can install TA-Lib binaries using your operating system's package manager. The process may vary depending on your operating system. If you let me know which operating system you're using, I can provide more specific instructions.

Once TA-Lib is installed successfully, you should be able to use the Python TA-Lib wrapper without any issues.

Regarding compatibility with Python versions, the project has been developed and tested on Python 3.6 but should work normally up to Python 3.11. However, please note that there is a small exception related to the Jupyter Notebook 'qqe_mod_clear.ipynb'. The notebook includes the 'nb_black' extension, which automatically corrects coding style based on the Black Lib. This extension may have issues under Python 3.11. If you encounter any problems with this extension, you can simply comment out the cell containing it to resolve the issue.

**Comment by edyatl** [comment]
**Closing the Issue Due to Inactivity**

Thank you for your feedback and the discussion. Since more than six months have passed without further activity or updates, I will be closing this issue for now. If you encounter any further problems or have additional questions, please feel free to reopen the issue or start a new one.

Thanks again for reaching out and for your interest in the project!
